rules:
  force-element-nesting:
    - 0
  leading-zero:
    - 1
    - include: true
  no-qualifying-elements:
    - 0
  no-url-protocols:
    - 0
  property-sort-order:
    - 0
  quotes:
    - 1
    - style: single
  indentation:
    - 1
    - size: 2
  variable-name-format:
    - 0
  class-name-format:
    - 0
  no-transition-all:
    - 0
  no-url-domains:
    - 0
